development:
  adapter: postgresql
  encoding: unicode
  database: potluck_development
  pool: 5



test:
  adapter: postgresql
  encoding: unicode
  database: potluck_test
  pool: 5



production:
  adapter: postgresql
  encoding: unicode
  host: ec2-54-204-45-196.compute-1.amazonaws.com
  database: d7itfciacqtru6
  user: ujiqgrvhwdpvnj
  password: ZbEoc7ERok6zxd5HW17xZCc_9d
  pool: 5

