---
development:
  :address: smtp.mandrillapp.com
  :port: 587
  :authentication: login
  :user_name: loganbestwick@gmail.com
  :password: K1l4hvJHdJBpHJikapIeYQ
  :domain: yourdomain.com
production:
  :address: smtp.mandrillapp.com
  :port: 587
  :authentication: login
  :user_name: loganbestwick@gmail.com
  :password: K1l4hvJHdJBpHJikapIeYQ
  :domain: yourdomain.com
